models:
  image: tp33/django
  container_name: models
  external_links:
    - mysql:db
  entrypoint: ./startup.sh
  volumes:
    - ./models:/app
  ports:
    - "8001:8000"
  command: bash -c "mod_wsgi-express start-server --working-directory . --reload-on-changes ./app-microservices/wsgi.py"

exp:
  image: tp33/django
  container_name: exp
  links:
    - models:models-api
    - kafka:kafka
    - es:es
  ports:
    - "8002:8000"
  volumes:
    - ./exp:/app/
    - ./data:/data
  command: "mod_wsgi-express start-server --reload-on-changes ./exp/wsgi.py"

web:
  image: tp33/django
  container_name: web
  links:
    - exp:exp-api
    - nginx:nginx
  ports:
    - "8000:8000"
  volumes:
    - ./web:/app
  command: "mod_wsgi-express start-server --reload-on-changes ./web/wsgi.py"

web2: #for load balancing
  image: tp33/django
  container_name: web2
  links:
    - exp:exp-api
    - nginx:nginx
  ports:
    - "8003:8000"
  volumes:
    - ./web:/app
  command: "mod_wsgi-express start-server --reload-on-changes ./web/wsgi.py"

kafka:
  image: spotify/kafka
  container_name: kafka
  environment:
    ADVERTISED_HOST: kafka
    ADVERTISED_PORT: 9092
  hostname: kafka
   
es:
  image: elasticsearch:2.0
  container_name: es
  ports:
    - "9200:9200"

batch:
  image: tp33/django
  container_name: batch
  links:
    - kafka:kafka
    - es:es
    - models:models-api
  volumes:
    - ./:/app
  entrypoint: ./startKafkaStuff.sh

haproxy:
  image: haproxy:1.8
  container_name: haproxy
  links:
    - web:web-api
    - web2:web-api2
  ports:
    - "80:80"
  volumes:
    - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg

selenium-chrome:
  image: selenium/standalone-chrome
  container_name: selenium-chrome
  links:
    - web:web
  ports:
    - "4444:4444"

selenium-test:
  image: tp33/django
  container_name: selenium-test
  links:
    - selenium-chrome:selenium-chrome
    - web:web
  volumes:
    - ./app/selenium:/app
  command: bash -c "sleep 10 && pip install selenium==3.141.0 && python selenium_test.py"

nginx:
  image: nginx:1.15.7
  container_name: nginx
  volumes:
    - ./web/web_frontend/static:/usr/share/nginx/html:ro
  ports:
    - "8081:80"

spark-master:
  image: gettyimages/spark
  command: bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
  container_name: spark-master
  hostname: spark-master
  environment:
    MASTER: spark://spark-master:7077
    SPARK_CONF_DIR: /conf
  links:
    - models:models-api
    - kafka:kafka
  expose:
    - 7001
    - 7002
    - 7003
    - 7004
    - 7005
    - 7006
    - 7077
    - 6066
  ports:
    - 4040:4040
    - 6066:6066
    - 7077:7077
    - 8080:8080
  volumes:
    - ./data:/tmp/data
  #entrypoint: ./data/startSpark.sh

spark-worker:
  image: gettyimages/spark
  command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
  container_name: spark-worker
  hostname: spark-worker
  environment:
    SPARK_CONF_DIR: /conf
    SPARK_WORKER_CORES: 2
    SPARK_WORKER_MEMORY: 512m
    SPARK_WORKER_PORT: 8881
    SPARK_WORKER_WEBUI_PORT: 8081
  links:
    - spark-master
  expose:
    - 7012
    - 7013
    - 7014
    - 7015
    - 7016
    - 8881
  ports:
    - 8082:8082
  volumes:
    - ./data:/tmp/data
