models:
  image: tp33/django
  container_name: models
  external_links:
    - mysql:db
  entrypoint: ./startup.sh
  volumes:
    - ./models:/app
  ports:
    - "8001:8000"
  command: bash -c "mod_wsgi-express start-server --working-directory . --reload-on-changes ./app-microservices/wsgi.py"

exp:
  image: tp33/django
  container_name: exp
  links:
    - models:models-api
    - kafka:kafka
  ports:
    - "8002:8000"
  volumes:
    - ./exp:/app
  command: "mod_wsgi-express start-server --reload-on-changes ./exp/wsgi.py"

web:
  image: tp33/django
  container_name: web
  links:
    - exp:exp-api
  ports:
    - "8000:8000"
  volumes:
    - ./web:/app
  command: "mod_wsgi-express start-server --reload-on-changes ./web/wsgi.py"

kafka:
  image: spotify/kafka
  container_name: kafka
  environment:
    ADVERTISED_HOST: kafka
    ADVERTISED_PORT: 9092
  hostname: kafka
   
es:
  image: elasticsearch:2.0
  container_name: es
  ports:
    - "9200:9200"

batch:
  image: tp33/django
  container_name: batch
  links:
    - kafka:kafka
    - es:es
  volumes:
    - ./:/app
  entrypoint: ./startES.sh
  #command: "python esScript.py" #<run a python script that pulls messages from Kafka and indexs that in ES>