models:
  image: brianyu/django
  external_links:
    - mysql:db
  volumes:
    - ./:/app
  ports:
    - "8001:8000"
  command: bash -c "mod_wsgi-express start-server --working-directory . --reload-on-changes ./app-microservices/wsgi.py"