# Generated by Django 2.1 on 2018-10-30 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20181029_0147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authenticator',
            fields=[
                ('authenticator', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('date_created', models.DateField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='salt',
        ),
        migrations.AddField(
            model_name='authenticator',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
    ]
