# Generated by Django 2.1 on 2018-10-29 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20181029_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='salt',
            field=models.TextField(),
        ),
    ]
