# Generated by Django 2.1 on 2018-10-30 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20181030_0342'),
        ('app', '0010_remove_user_salt'),
    ]

    operations = [
    ]
